"""Fix backref conflict

Revision ID: 6289e74db015
Revises: 
Create Date: 2024-06-12 22:38:14.182948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6289e74db015'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_ibfk_1', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'cover', ['cover_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('books_genres_ibfk_1', 'books_genres', type_='foreignkey')
    op.drop_constraint('books_genres_ibfk_2', 'books_genres', type_='foreignkey')
    op.create_foreign_key(None, 'books_genres', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books_genres', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('review_ibfk_2', 'review', type_='foreignkey')
    op.drop_constraint('review_ibfk_1', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_ibfk_1', 'review', 'book', ['book_id'], ['id'])
    op.create_foreign_key('review_ibfk_2', 'review', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.drop_constraint(None, 'books_genres', type_='foreignkey')
    op.create_foreign_key('books_genres_ibfk_2', 'books_genres', 'genre', ['genre_id'], ['id'])
    op.create_foreign_key('books_genres_ibfk_1', 'books_genres', 'book', ['book_id'], ['id'])
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_ibfk_1', 'book', 'cover', ['cover_id'], ['id'])
    # ### end Alembic commands ###
